FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements/train.txt /tmp/requirements-train.txt
RUN pip install --no-cache-dir -r /tmp/requirements-train.txt

COPY app ./app
COPY data ./data
COPY artifacts ./artifacts

CMD ["python", "-m", "app.training.train_with_mlflow"]
