FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements/frontend.txt /tmp/requirements-frontend.txt
RUN pip install --no-cache-dir -r /tmp/requirements-frontend.txt

COPY app ./app
COPY data ./data

EXPOSE 8501

CMD ["streamlit", "run", "app/frontend/streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]
